---
title: Safari
timezone: UTC

collections:
  questions:
    output: true
    permalink: "/:title"

defaults:
- scope:
    path: ''
    type: questions
  values:
    layout: post
    is_question: true
- scope:
    path: ''
  values:
    layout: intro

description: POLISOCIAL è il programma di impegno e responsabilità sociale presso
  il Politecnico di Milano. www.polisocial.polimi.it
baseurl: "/safari-njema"
url: https://densitydesign.github.io
markdown: kramdown
kramdown:
  parse_block_html: true
