title: Safari Njema
author: Polisocial logo
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This project has received funding from the European Union’s Seventh Framework Programme for research, technological development and demonstration under grant agreement n° 288964
baseurl: "/safari-njema" # the subpath of your site, e.g. /blog
url: "https://densitydesign.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
markdown: kramdown
kramdown:
  parse_block_html: true

collections:
  questions:
    output: true
    permalink: /:title

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      is_question: true
  - scope:
      path: ""
    values:
      layout: "intro"

# Build settings
plugins:
  - jekyll-feed
