---
title: Safari
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  questions:
    title: Questions
    output: true
    permalink: "/:title"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: questions
  values:
    layout: post
    is_question: true
- scope:
    path: ''
  values:
    layout: intro
description: POLISOCIAL è il programma di impegno e responsabilità sociale presso
  il Politecnico di Milano. www.polisocial.polimi.it
baseurl: "/"
url: https://www.safari-njema.polimi.it/
markdown: kramdown
kramdown:
  parse_block_html: true
